### ISSUE TITLE
Atom/RSS feed

### ISSUE THREAD

**Issue by MFAshby** [kristoff-it/zine#28]
I really like it when good blogs have RSS (or atom, whatever) feeds that I can subscribe to, it means I don't need to miss a post but I also don't have to hand out my email or anything.

I have RSS on my own blog which I am trying to migrate from hugo to zine, and the lack of RSS feed generation is stopping me.

**Comment by kristoff-it** [comment]
Take a look at https://github.com/kristoff-it/kristoff.it.

The current way of generating an RSS feed is by generating it as an `alternative` of a section page. This is not a solution that covers 100% of usecases, so hopefully it's enough for you. If it's not, let me know.

**Comment by MFAshby** [comment]
I'll try it out, thanks!

**Comment by MFAshby** [comment]
It works, thanks @kristoff-it . 

Only thing I am missing from Hugo is the ability to put the whole content in the RSS feed. I can likely do without this for now. 

Here's my rss.xml template:
```
<rss version="2.0" 
  xmlns:atom="http://www.w3.org/2005/Atom"
  xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>Home on mfashby.net</title>
    <link>https://mfashby.net/</link>
    <description>Recent content in Home on mfashby.net</description>
    <language>en-gb</language>
    <lastBuildDate>Sun, 03 Mar 2024 19:31:27 +0000</lastBuildDate>
    <atom:link href="https://mfashby.net/index.xml" rel="self" type="application/rss+xml"/>
    <item inline-loop="$page.subpages()">
      <title var="$loop.it.title"></title>
      <link var="$loop.it.permalink()"></link>
      <pubDate var="$loop.it.date.formatHTTP()"></pubDate>
      <guid var="$loop.it.permalink()"></guid>
      <description var="$loop.it.description"></description>
      <content:encoded var="$loop.it.content"></content:encoded> <!-- This doesn't work, an empty tag is emitted -->
    </item>
  </channel>
</rss>
```
