### ISSUE TITLE
settle on a date formatting syntax and create a proper paser for it

### ISSUE THREAD

**Issue by kristoff-it** [kristoff-it/zine#32]
Currently date formatting syntax is based on Go's "magic date", but a proprer conscious decision on what syntax to use should be made.

Additionally, currently a handful of ad-hoc formats are supported but we should eventually build a proper parser for it. 

Building a parser for the Go magic date format might also give insight on how good the format.

**Comment by nkoehring** [comment]
Not sure, if Go's magic date format is a good choice. Many people find it just confusing. Also, there seems to be no Zig implementation for it, yet. An easier way to go, would be to just use some existing date parsing library, that works with standard date format specifiers.

**Comment by kristoff-it** [comment]
I'm not interested in the easy path and I personally find it much harder to remember what all the YyMmDdHhSs identifiers do vs Go's magic date. 

That said, even if I prefer Go's approach over the aforementioned syntax, I can buy the argument that there might be better approaches than Go's. If you happen to can think of a third option to escape the current dichotomy I'm in, I'd be happy talk about it.

**Comment by kristoff-it** [comment]
The datetime dependency we use added native support for Go format strings so we'll go with that for the time being.
