### ISSUE TITLE
Page `permalink()` ignores subroutes in the `host_url`

### ISSUE THREAD

**Issue by Arnau478** [kristoff-it/zine#38]
When `host_url` is given a URL that contains a route (e.g. `https://example.org/foo`) it does not take it into account. Thus, the permalink to `bar` is `https://example.org/bar` instead of `https://example.org/foo/bar`.

**Comment by Arnau478** [comment]
Okay, so it actually makes sense for zine to behave the way it does not, as permalinks are relative to `/`. Still, there should be a way to specify a subroute. It could be done with `host_url` or with something completely different. But either way, it should be possible to have the site under `/foo/bar/baz` or something.

**Comment by kristoff-it** [comment]
in your site definition struct use `output_prefix` (set to `"foo"`) instead of putting that inside of your host url. Should solve all your problems.

Zine needs a check to error out when somebody puts a path inside the host_url.

**Comment by Arnau478** [comment]
Okay, it does work now... Sorry, the fact that I got no error made me think that was the intended way. Either way, thanks for the help.
