### ISSUE TITLE
Markdown error message line numbers don't take into account front matter

### ISSUE THREAD

**Issue by MatthiasPortzel** [kristoff-it/zine#45]
The line numbers printed by this bit of code are offset from the start of the markdown document, but these are incorrect if the document has front matter.

https://github.com/kristoff-it/zine/blob/ebd8796f4a1c20c938693431aa638fbaa35a9fe4/src/exes/markdown-renderer.zig#L248

**Comment by kristoff-it** [comment]
Zine v0.4.0 has a proper implementation of content files that (among other things) solve the frontmatter offset problem.
