### ISSUE TITLE
Add git info to `$build`

### ISSUE THREAD

**Issue by kristoff-it** [kristoff-it/zine#49]
Add to `$build` in SuperHTML the ability to obtain git information when in a repository.

We could discuss what the API / exact capabilities should look like, but I'm imagining something like:

- current commit hash
- tag if any
- commit date and author info
- branch

One important aspect to consider is that this info should become a data dependency of the page, meaning that a page that tries to show any of this info should be rebuilt if any changes.

Here's how to get started:

1. Create `src/context/Git.zig`
2. Give to the top-level struct all the boilerplate that other types have  (description, dot function, builtins struct)
3. Add fields to it that contain the data described above
4. Add an init function to it that sets those values
5. Add to `$build` (`src/context/Build.zig`) a field called `_git`
6. In `$build`'s init function call git's init function.
7. Add to `$build` a getter that returns the value of `_git`  if we're in a git repo, or an error otherwise. To implement this you can add a `_in_repo` bool field to the git instance that gets set when inited.

This will setup everything except the data dependency, which is something we can work on once this is done.

**Comment by Sc3l3t0n** [comment]
Hi @kristoff-it,

I'm interested in taking on this issue. I've already managed to get git information working within the templates and now just need to implement the logic behind the git struct.

Regarding the implementation, should the git information be retrieved by using the CLI, or should we parse it directly from the repository ourselves?

I'm excited to contribute to this—please let me know if I can proceed.
I appreciate any guidance you can provide.

Best regards,

Marlon

**Comment by kristoff-it** [comment]
This is now available in v0.7.2. I've moved some of the code from the PR around in order to integrate with the cache system correctly.
