### ISSUE TITLE
Links to RSS feeds

### ISSUE THREAD

**Issue by MasonRemaley** [kristoff-it/zine#52]
I tried to create a link to the RSS feed of a devlog on that devlog via this smd:
```md
[link](index.xml)
```

But I got this output:
```
An asset referenced in a content file is missing. 

[missing_asset] unable to find 'index.xml'
(log.smd) content/log.smd:17:1: 
    [link](index.xml)
    ^^^^^^^^^^^^^^^^
```

I'm guessing some logic just needs to be added to the path checker to handle this case (but if there's just some other syntax I'm missing let me know!)

For anyone who finds this issue looking for a workaround, you can bypass the validation when needed by making the link with embedded HTML:
````
```=html
<a href="index.xml">link</a>
```
````

**Comment by fabioarnold** [comment]
According to [the docs](https://zine-ssg.io/docs/superhtml/scripty/#Alternative) you can use:
```html
<ctx alt="$page.alternative('rss')">
  <a href="$ctx.alt.link()" 
     type="$ctx.alt.type" 
     text="$ctx.alt.name"
  ></a>
</ctx>
```
(but it doesn't currently work for me 😅)

**Comment by kristoff-it** [comment]
I've implemented all the missing bits to make this work in a straightforward manner, see the updated FAQ section: https://zine-ssg.io/docs/frequent/#rss
