### ISSUE TITLE
"valid HTML"

### ISSUE THREAD

**Issue by 3052** [kristoff-it/zine#54]
I saw this:

> SuperHTML templates are valid HTML and the templating logic is expressed through scripted attributes.

~~~html
<ul :loop="$page.tags">
  <li :text="$loop.it"></li>
</ul>
~~~

https://kristoff.it/blog/zine-ssg-zig/

and immediately my brain said "thats not valid HTML". looks like my suspicion was correct:

> The Namespaces in XML Recommendation [[XML Names]](https://www.w3.org/TR/2008/REC-xml-20081126/#xml-names) assigns a meaning to names containing colon characters. Therefore, authors should not use the colon in XML names except for namespace purposes, but XML processors must accept the colon as a name character.

https://www.w3.org/TR/2008/REC-xml-20081126/#sec-common-syn

**Comment by kristoff-it** [comment]
I'm following the HTML living spec from whatwg and there is no special rules for colon presence in html attributes.
https://html.spec.whatwg.org/#attributes-2


Pedantry aside, SuperHTML is a templating language so special attributes also never get included in the final output.
