### ISSUE TITLE
feat: facilitate #fragment linking inside pages

### ISSUE THREAD

**Issue by softmoth** [kristoff-it/zine#56]
There should be `name` or `id` attributes in the HTML output.

For example, https://ziglang.org/learn/overview/ . It should be possible to link directly to the figure called `19-generics.zig`, or _at least_ to the heading `Generic data structures and functions`.

**Comment by kristoff-it** [comment]
It is already possible, one just needs to specify the id property of a content directive inside of supermd, it was just not done for that page in particular.
