### ISSUE TITLE
SuperMD span support, PRETTY PLEASE

### ISSUE THREAD

**Issue by ksed** [kristoff-it/zine#75]
Zine currently supports `SECTION` directive for formatting a block of text but no in-line directive within a SuperMD document (e.g. \<span>\</span>).

The ability to apply CSS formats to a SECTION is WONDEFUL. But I would really like to also be able to apply CSS to certain selection of text within a SuperMD file (i.e. beyond what Markdown already supports like bold, italic). And it seems to me that this feature would be very similar to implement to the `$link` directive.

e.g.
`My paragraph/table includes [this span text]($span.attrs("mycolor","myfont")) and more.`

FWIW, I think this SPAN-support is pretty much the only missing functionality preventing me from switching from Hugo today. I otherwise really like how simple the Zine syntax is compared to Hugo.

**Comment by ksed** [comment]
FWIW, I think this SPAN-support is pretty much the only missing functionality preventing me from switching from Hugo. I otherwise really like how simple the Zine syntax is compared to Hugo.

**Comment by kristoff-it** [comment]
Implemented as `$text` in v0.7.1, enjoy.

**Comment by ksed** [comment]
Awesome! THANKS!
